augmentations:
  - type: Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  - type: Resize
    height: 128
    width: 128
  - type: ColorJitter
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.2
    p: 0.5
  - type: GaussNoise
    var_limit: [10.0, 50.0]
    p: 0.5
  - type: CoarseDropout
    max_holes: 8
    max_height: 8
    max_width: 8
    min_holes: 1
    min_height: 1
    min_width: 1
    fill_value: 0
    p: 0.5
  - type: Blur
    blur_limit: 7
    p: 0.5
  - type: OpticalDistortion
    distort_limit: 0.05
    shift_limit: 0.05
    p: 0.3
  - type: GridDistortion
    num_steps: 5
    distort_limit: 0.3
    p: 0.3
  - type: ElasticTransform
    alpha: 1
    sigma: 50
    alpha_affine: 50
    p: 0.3
  - type: RandomRotation
    degrees: 10

root_dir:  ${hydra:runtime.cwd}
data_dir: ${root_dir}/dataset
images_dir: ${data_dir}/train/contexts_prompts
labels_file: ${root_dir}/list_of_cheese.txt
batch_size: 32
save_dir: ${data_dir}/train/augmented

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/
  job:
    chdir: true
  