# parameters for the curator
root_dir:  ${hydra:runtime.cwd}
data_dir: ${root_dir}/dataset
images_dir: ${data_dir}/train/contexts_prompts
labels_file: ${root_dir}/list_of_cheese.txt
batch_size: 32

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/
  job:
    chdir: true