_target_: torchvision.transforms.Compose
transforms:
  # random transforms
  - _target_: torchvision.transforms.RandomHorizontalFlip
  - _target_: torchvision.transforms.RandomRotation
    degrees: 15
  - _target_: torchvision.transforms.RandomVerticalFlip
  - _target_: torchvision.transforms.ColorJitter
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.2
  - _target_: torchvision.transforms.GaussianBlur
    kernel_size: 3
  - _target_: torchvision.transforms.ElasticTransform
    alpha: 1.0
    sigma: 50.0
  - _target_: torchvision.transforms.RandomPosterize
    bits: 4
  #mandatory transforms
  - _target_: torchvision.transforms.Resize
    size: [224, 224]
  - _target_: torchvision.transforms.ToTensor
  - _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]