_target_: data.dataset_generators.contexts.ContextsPromptsDatasetGenerator
generator: ${image_generator}
cheese_description: ${root_dir}/cheese_description.yaml
batch_size: ${batch_size}
output_dir: ${data_dir}/train/contexts_prompts
