defaults:
  - train_transform: simple
  - test_transform: simple

name: contexts
num_classes: 37
batch_size: 128
num_workers: 8
train_path: ${data_dir}/train/contexts_prompts
# train_path: ${data_dir}/val
real_images_val_path: ${data_dir}/val
test_path: ${data_dir}/test
